project:
  title: >
    Machine Learning Explainability:
    Exploring Automated Decision-Making Through Transparent Modelling and
    Peeking Inside Black Boxes
  type: website
  render:
    - slides/
    - "!slides/_template.qmd"
    - "!slides/_web_readme.md"
    - "!README.md"
    - "!demos/"
    - "!_code/"
  resources:
    - assets
#    - "**/rise.css"
  output-dir: _build
  execute-dir: file
 
toc: true
number-sections: false
bibliography: bibliography.bib

author: "Kacper Sokol"

jupyter: python3
execute:
  enabled: true
custom-paths:
  figures: /assets/figures
  ipynb-figures: ../../assets/figures
  images: /assets/images
  ipynb-images: ../../assets/images
subs:
  ctd: "&nbsp;&nbsp;&nbsp;{{< fa arrow-alt-circle-up >}}"

format:
  revealjs: 
    from: markdown+emoji
    toc: true
    toc-depth: 1
    toc-title: "Topics"
#    theme: moon
    theme: solarized
    width: 1680
#  ipynb:
#    from: ipynb+emoji

website:
  sidebar:
    style: floating
    search: false
    collapse-level: 2
    title: Slides
    contents:
      - section: Introduction
        contents:
          - text: About the Course
            href: slides/1_introduction/course.qmd
          - text: Preliminaries
            href: slides/1_introduction/preliminaries.qmd
          - text: Taxonomy
            href: slides/1_introduction/taxonomy.qmd
          - text: Humans
            href: slides/1_introduction/humans.qmd
          - text: Definitions
            href: slides/1_introduction/definitions.qmd
          - text: Evaluation
            href: slides/1_introduction/evaluation.qmd
          - text: Data Sets and Models
            href: slides/1_introduction/data.qmd
      - section: Transparent Modelling
        contents:
          - text: Data Explainability
            href: slides/2_glass-box/data.qmd
          - text: Linear Model
            href: slides/2_glass-box/linear.qmd
#          - text: Logistic Model
#            href: slides/2_glass-box/logistic.qmd
#          - text: Generalised Linear Model
#            href: slides/2_glass-box/glm.qmd
          - text: Decision Tree
            href: slides/2_glass-box/tree.qmd
#          - text: Decision Rules
#            href: slides/2_glass-box/rules.qmd
#          - text: Neighbour-based
#            href: slides/2_glass-box/neighbours.qmd
      - section: Feature-based Explainability
        contents:
          - text: Permutation Feature Importance
            href: slides/3_feature-based/pfi.qmd
          - text: Individual Conditional Expectation
            href: slides/3_feature-based/ice.qmd
          - text: Partial Dependence
            href: slides/3_feature-based/pd.qmd
          - text: Marginal Effect
            href: slides/3_feature-based/me.qmd
          - text: Accumulated Local Effect
            href: slides/3_feature-based/ale.qmd
#          - text: Feature Interaction
#            href: slides/3_feature-based/fi.qmd
#          - text: Functional Decomposition
#            href: slides/3_feature-based/fd.qmd
      - section: Meta-Explainers
        contents:
          - text: Surrogate Explainers
            href: slides/5_meta/surrogate.qmd
#          - text: "Surrogate Explainers: LIME"
#            href: slides/5_meta/lime.qmd
#          - text: "Surrogate Explainers: LIMEtree"
#            href: slides/5_meta/limetree.qmd
#          - text: RuleFit
#            href: slides/5_meta/rulefit.qmd
#          - text: Anchors
#            href: slides/5_meta/anchors.qmd
#          - text: SHAP
#            href: slides/5_meta/shap.qmd
#      - section: Instance-based Explainability
#        contents:
#          - text: Exemplars
#            href: slides/4_instance-based/exemplars.qmd
#          - text: Prototypes and Criticisms
#            href: slides/4_instance-based/prototypes_criticisms.qmd
#          - text: Counterfactuals
#            href: slides/4_instance-based/counterfactuals.qmd
#      - section: Demos
#        contents:
#          - text: Surrogate Explainers Demo
#            href: demos/5_meta/surrogates.ipynb
